# Generated by Django 2.2.7 on 2019-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esayblog', '0002_blogpost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
